"""Typed, permission-checked tools exposed to the AI model."""

from services.ai.tools.approvals import build_approval_summary
from services.ai.tools.context import (
    CapabilityResolver,
    EventEmitter,
    ToolContext,
    ToolHandler,
    ToolSpec,
    _safe_relative_path,
    canonical_arguments,
)
from services.ai.tools.files import _safe_css_log_name
from services.ai.tools.registry import TOOL_SPECS, TOOLS_BY_NAME, execute_tool, tool_definitions
from services.ai.tools.schemas import (
    ApplyManagedPluginUpgradeInput,
    ApplyPluginPlanInput,
    ApplyServerStartupPlanInput,
    ApplyWorkshopPlanInput,
    ChangeCurrentMapInput,
    CSSLogListInput,
    CSSLogReadInput,
    DiagnosticExecuteInput,
    DiagnosticPlanInput,
    DiagnosticRunInput,
    EmptyInput,
    FilePatchInput,
    FileReadInput,
    FileSearchInput,
    GameConsoleCommandInput,
    GameConsoleReadInput,
    GitHubApplyInput,
    GitHubInspectInput,
    GitHubPlanInput,
    GitHubSearchInput,
    KnowledgeInput,
    ManagedPluginUpgradeInput,
    MapPoolSearchInput,
    PluginPlanInput,
    PluginSearchInput,
    SavedHostCommandInput,
    ServerControlInput,
    ServerOperationInput,
    ServerStartupPlanInput,
    TailLogInput,
    ToolInput,
    WorkshopPlanInput,
)

__all__ = [
    "ApplyManagedPluginUpgradeInput",
    "ApplyPluginPlanInput",
    "ApplyServerStartupPlanInput",
    "ApplyWorkshopPlanInput",
    "CSSLogListInput",
    "CSSLogReadInput",
    "CapabilityResolver",
    "ChangeCurrentMapInput",
    "DiagnosticExecuteInput",
    "DiagnosticPlanInput",
    "DiagnosticRunInput",
    "EmptyInput",
    "EventEmitter",
    "FilePatchInput",
    "FileReadInput",
    "FileSearchInput",
    "GameConsoleCommandInput",
    "GameConsoleReadInput",
    "GitHubApplyInput",
    "GitHubInspectInput",
    "GitHubPlanInput",
    "GitHubSearchInput",
    "KnowledgeInput",
    "ManagedPluginUpgradeInput",
    "MapPoolSearchInput",
    "PluginPlanInput",
    "PluginSearchInput",
    "SavedHostCommandInput",
    "ServerControlInput",
    "ServerOperationInput",
    "ServerStartupPlanInput",
    "TOOL_SPECS",
    "TOOLS_BY_NAME",
    "TailLogInput",
    "ToolContext",
    "ToolHandler",
    "ToolInput",
    "ToolSpec",
    "WorkshopPlanInput",
    "_safe_css_log_name",
    "_safe_relative_path",
    "build_approval_summary",
    "canonical_arguments",
    "execute_tool",
    "tool_definitions",
]
