"""
Core modules for CS2 Server Manager
"""
from .config import settings, Settings
from .models import Base, Server, DeploymentLog, MonitoringLog, ServerStatus, AuthType, User, InitializedServer, ScheduledTask, CustomCommand, MarketPlugin, ManagedPlugin, PluginConfigSource, PluginCategory, SSHServerSudo, SystemSettings, PasswordResetToken, DEFAULT_PLUGIN_CONFIG_SOURCE_PATH
from .schemas import (
    ServerCreate, ServerUpdate, ServerResponse, ServerResponseWithUser,
    ServerAction, ActionResponse, DeploymentLogResponse,
    BatchActionRequest, BatchActionResponse, BatchInstallPluginsRequest,
    BatchSendCommandRequest,
    UserCreate, UserLogin, UserResponse, Token, TokenData,
    PasswordReset, UserProfileUpdate,
    ApiKeyResponse, ApiKeyGenerate,
    SteamApiKeyResponse, GitHubTokenStatusResponse, GenerateServerTokenRequest, GenerateServerTokenResponse,
    S3SettingsResponse, S3SettingsUpdate, S3BackupItem, S3RestoreRequest,
    CleanupItem, CleanupWorkshopSummary, CleanupScanResponse,
    CleanupDeleteRequest, CleanupFailedItem, CleanupDeleteResponse,
    A2SServerInfo, A2SPlayerInfo, A2SCachedData, A2SCacheResponse,
    InitializedServerCreate, InitializedServerResponse, InitializedServerListItem,
    ScheduledTaskCreate, ScheduledTaskUpdate, ScheduledTaskResponse,
    CustomCommandCreate, CustomCommandUpdate, CustomCommandExecuteRequest, CustomCommandResponse,
    GitHubReleaseAsset, GitHubRelease, GitHubReleasesResponse,
    ArchiveContentItem, ArchiveAnalysisResponse,
    GitHubPluginInstallRequest, GitHubPluginInstallResponse,
    MarketPluginCreate, MarketPluginUpdate, MarketPluginResponse, MarketPluginListResponse,
    MarketPluginInstallRequest, GitHubRepoInfo, DependencyInfo,
    PluginAutoUpdateSettings, ManagedPluginCreate, ManagedPluginUpdate,
    ManagedPluginResponse, PluginAutoUpdateResponse,
    PluginUninstallRequest, PluginUninstallResponse,
    InstalledPluginFile, InstalledPluginAnalysisResponse,
    MetamodStatusResponse,
    SystemSettingsResponse, SystemSettingsUpdate,
    ForgotPasswordRequest, ResetPasswordRequest,
    DiscordSettingsResponse, DiscordSettingsUpdate, DiscordTestRequest,
    GmailCredentialsUploadRequest, EmailTestRequest,
    GoogleOAuthRequest
)
from .database import get_db, init_db, engine, async_session_maker, migrate_db
from .auth import (
    get_password_hash, verify_password, get_password_hash_async, verify_password_async,
    create_access_token, set_web_session_cookie, clear_web_session_cookie,
    get_current_user, get_current_active_user, get_current_admin_user,
    get_current_web_user, get_current_web_admin, authenticate_websocket,
    get_optional_current_user, get_user_from_api_key, get_current_user_flexible
)
from .utils import generate_api_key, verify_api_key_format, get_current_time
from .logging_config import setup_logging, _get_log_level

__all__ = [
    'settings',
    'Settings',
    'Base',
    'Server',
    'DeploymentLog',
    'MonitoringLog',
    'User',
    'InitializedServer',
    'ScheduledTask',
    'CustomCommand',
    'MarketPlugin',
    'ManagedPlugin',
    'PluginConfigSource',
    'DEFAULT_PLUGIN_CONFIG_SOURCE_PATH',
    'PluginCategory',
    'SSHServerSudo',
    'SystemSettings',
    'PasswordResetToken',
    'ServerStatus',
    'AuthType',
    'ServerCreate',
    'ServerUpdate',
    'ServerResponse',
    'ServerResponseWithUser',
    'ServerAction',
    'ActionResponse',
    'DeploymentLogResponse',
    'BatchActionRequest',
    'BatchActionResponse',
    'BatchInstallPluginsRequest',
    'BatchSendCommandRequest',
    'UserCreate',
    'UserLogin',
    'UserResponse',
    'Token',
    'TokenData',
    'PasswordReset',
    'UserProfileUpdate',
    'ApiKeyResponse',
    'ApiKeyGenerate',
    'SteamApiKeyResponse',
    'GitHubTokenStatusResponse',
    'S3SettingsResponse',
    'S3SettingsUpdate',
    'S3BackupItem',
    'S3RestoreRequest',
    'CleanupItem',
    'CleanupWorkshopSummary',
    'CleanupScanResponse',
    'CleanupDeleteRequest',
    'CleanupFailedItem',
    'CleanupDeleteResponse',
    'GenerateServerTokenRequest',
    'GenerateServerTokenResponse',
    'A2SServerInfo',
    'A2SPlayerInfo',
    'A2SCachedData',
    'A2SCacheResponse',
    'InitializedServerCreate',
    'InitializedServerResponse',
    'InitializedServerListItem',
    'ScheduledTaskCreate',
    'ScheduledTaskUpdate',
    'ScheduledTaskResponse',
    'CustomCommandCreate',
    'CustomCommandUpdate',
    'CustomCommandExecuteRequest',
    'CustomCommandResponse',
    'GitHubReleaseAsset',
    'GitHubRelease',
    'GitHubReleasesResponse',
    'ArchiveContentItem',
    'ArchiveAnalysisResponse',
    'GitHubPluginInstallRequest',
    'GitHubPluginInstallResponse',
    'MarketPluginCreate',
    'MarketPluginUpdate',
    'MarketPluginResponse',
    'MarketPluginListResponse',
    'MarketPluginInstallRequest',
    'PluginAutoUpdateSettings',
    'ManagedPluginCreate',
    'ManagedPluginUpdate',
    'ManagedPluginResponse',
    'PluginAutoUpdateResponse',
    'GitHubRepoInfo',
    'DependencyInfo',
    'PluginUninstallRequest',
    'PluginUninstallResponse',
    'InstalledPluginFile',
    'InstalledPluginAnalysisResponse',
    'MetamodStatusResponse',
    'SystemSettingsResponse',
    'SystemSettingsUpdate',
    'DiscordSettingsResponse',
    'DiscordSettingsUpdate',
    'DiscordTestRequest',
    'ForgotPasswordRequest',
    'ResetPasswordRequest',
    'GmailCredentialsUploadRequest',
    'EmailTestRequest',
    'GoogleOAuthRequest',
    'get_db',
    'init_db',
    'migrate_db',
    'engine',
    'async_session_maker',
    'get_password_hash',
    'verify_password',
    'get_password_hash_async',
    'verify_password_async',
    'create_access_token',
    'set_web_session_cookie',
    'clear_web_session_cookie',
    'get_current_user',
    'get_current_active_user',
    'get_current_admin_user',
    'get_current_web_user',
    'get_current_web_admin',
    'authenticate_websocket',
    'get_optional_current_user',
    'get_user_from_api_key',
    'get_current_user_flexible',
    'generate_api_key',
    'verify_api_key_format',
    'get_current_time',
    'setup_logging',
    '_get_log_level',
]
