"""PostgreSQL application schema baseline

Revision ID: 0001_postgresql_baseline
Revises:
Create Date: 2026-08-25 12:46:58.326569
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001_postgresql_baseline"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_system_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=True),
        sa.Column("model", sa.String(length=255), nullable=True),
        sa.Column("api_key_encrypted", sa.Text(), nullable=True),
        sa.Column("admin_prompt", sa.Text(), nullable=True),
        sa.Column(
            "private_endpoint_allowlist", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("reasoning_effort", sa.String(length=16), nullable=True),
        sa.Column("temperature", sa.Float(), nullable=True),
        sa.Column("top_p", sa.Float(), nullable=True),
        sa.Column("max_completion_tokens", sa.Integer(), nullable=False),
        sa.Column("token_limit_parameter", sa.String(length=32), nullable=False),
        sa.Column("frequency_penalty", sa.Float(), nullable=True),
        sa.Column("presence_penalty", sa.Float(), nullable=True),
        sa.Column("verbosity", sa.String(length=16), nullable=True),
        sa.Column("parallel_tool_calls", sa.Boolean(), nullable=True),
        sa.Column("request_timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("history_retention_days", sa.Integer(), nullable=False),
        sa.Column("max_provider_rounds", sa.Integer(), nullable=False),
        sa.Column("max_tool_calls_per_round", sa.Integer(), nullable=False),
        sa.Column("provider_tested", sa.Boolean(), nullable=False),
        sa.Column("tool_calling_tested", sa.Boolean(), nullable=False),
        sa.Column("streaming_tested", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_system_settings")),
    )
    op.create_table(
        "deployment_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("output", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deployment_logs")),
    )
    op.create_index(
        "ix_deployment_logs_server_created",
        "deployment_logs",
        ["server_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deployment_logs_server_id"), "deployment_logs", ["server_id"], unique=False
    )
    op.create_table(
        "market_plugins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("github_url", sa.String(length=500), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("author", sa.String(length=255), nullable=True),
        sa.Column("version", sa.String(length=50), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "GAME_MODE",
                "ENTERTAINMENT",
                "UTILITY",
                "ADMIN",
                "PERFORMANCE",
                "LIBRARY",
                "OTHER",
                name="plugin_category",
                native_enum=False,
                create_constraint=False,
            ),
            nullable=False,
        ),
        sa.Column("tags", sa.Text(), nullable=True),
        sa.Column("is_recommended", sa.Boolean(), nullable=False),
        sa.Column("icon_url", sa.String(length=500), nullable=True),
        sa.Column("dependencies", sa.Text(), nullable=True),
        sa.Column("custom_install_path", sa.String(length=255), nullable=True),
        sa.Column("download_count", sa.Integer(), nullable=False),
        sa.Column("install_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.CheckConstraint(
            "category IN ('GAME_MODE', 'ENTERTAINMENT', 'UTILITY', 'ADMIN', "
            "'PERFORMANCE', 'LIBRARY', 'OTHER')",
            name="ck_market_plugins_plugin_category",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_plugins")),
    )
    op.create_index(
        op.f("ix_market_plugins_github_url"), "market_plugins", ["github_url"], unique=True
    )
    op.create_index(op.f("ix_market_plugins_title"), "market_plugins", ["title"], unique=False)
    op.create_table(
        "monitoring_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_monitoring_logs")),
    )
    op.create_index(
        op.f("ix_monitoring_logs_created_at"), "monitoring_logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_monitoring_logs_server_id"), "monitoring_logs", ["server_id"], unique=False
    )
    op.create_table(
        "system_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("default_proxy_mode", sa.String(length=50), nullable=False),
        sa.Column("github_proxy_url", sa.String(length=500), nullable=True),
        sa.Column("global_github_token", sa.String(length=255), nullable=True),
        sa.Column("email_enabled", sa.Boolean(), nullable=False),
        sa.Column("email_provider", sa.String(length=50), nullable=False),
        sa.Column("email_from_address", sa.String(length=255), nullable=True),
        sa.Column("email_from_name", sa.String(length=255), nullable=True),
        sa.Column("gmail_credentials_json", sa.Text(), nullable=True),
        sa.Column("gmail_token_json", sa.Text(), nullable=True),
        sa.Column("smtp_host", sa.String(length=255), nullable=True),
        sa.Column("smtp_port", sa.Integer(), nullable=True),
        sa.Column("smtp_username", sa.String(length=255), nullable=True),
        sa.Column("smtp_password", sa.String(length=255), nullable=True),
        sa.Column("smtp_use_tls", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_settings")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("api_key", sa.String(length=64), nullable=True),
        sa.Column("steam_api_key", sa.String(length=64), nullable=True),
        sa.Column("github_token", sa.String(length=255), nullable=True),
        sa.Column("s3_enabled", sa.Boolean(), nullable=False),
        sa.Column("s3_endpoint_url", sa.String(length=500), nullable=True),
        sa.Column("s3_region", sa.String(length=100), nullable=True),
        sa.Column("s3_bucket", sa.String(length=255), nullable=True),
        sa.Column("s3_access_key_id", sa.String(length=255), nullable=True),
        sa.Column("s3_secret_access_key", sa.String(length=255), nullable=True),
        sa.Column("s3_prefix", sa.String(length=255), nullable=True),
        sa.Column("s3_use_ssl", sa.Boolean(), nullable=False),
        sa.Column("s3_retention_count", sa.Integer(), nullable=True),
        sa.Column("google_id", sa.String(length=255), nullable=True),
        sa.Column("oauth_provider", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_api_key"), "users", ["api_key"], unique=True)
    op.create_index(op.f("ix_users_google_id"), "users", ["google_id"], unique=True)
    op.create_index("uq_users_email_ci", "users", [sa.literal_column("lower(email)")], unique=True)
    op.create_index(
        "uq_users_username_ci", "users", [sa.literal_column("lower(username)")], unique=True
    )
    op.create_table(
        "github_install_recipes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repo_url", sa.String(length=500), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("source_prefix", sa.String(length=500), nullable=False),
        sa.Column("target_prefix", sa.String(length=500), nullable=False),
        sa.Column("framework", sa.String(length=32), nullable=True),
        sa.Column("config_globs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("required_repositories", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("documentation_commit", sa.String(length=64), nullable=True),
        sa.Column("revision", sa.String(length=64), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_github_install_recipes_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_github_install_recipes")),
        sa.UniqueConstraint("repo_url", "revision", name="uq_github_recipe_revision"),
    )
    op.create_index(
        op.f("ix_github_install_recipes_repo_url"),
        "github_install_recipes",
        ["repo_url"],
        unique=False,
    )
    op.create_table(
        "initialized_servers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("ssh_port", sa.Integer(), nullable=False),
        sa.Column("ssh_user", sa.String(length=100), nullable=False),
        sa.Column("ssh_password", sa.String(length=255), nullable=False),
        sa.Column("game_directory", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_initialized_servers_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_initialized_servers")),
    )
    op.create_index(
        "ix_initialized_servers_user_created",
        "initialized_servers",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_initialized_servers_user_id"), "initialized_servers", ["user_id"], unique=False
    )
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_password_reset_tokens_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_password_reset_tokens")),
    )
    op.create_index(
        op.f("ix_password_reset_tokens_token"), "password_reset_tokens", ["token"], unique=True
    )
    op.create_index(
        op.f("ix_password_reset_tokens_user_id"), "password_reset_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "plugin_conflict_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plugin_a_id", sa.Integer(), nullable=False),
        sa.Column("plugin_b_id", sa.Integer(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.CheckConstraint(
            "plugin_a_id < plugin_b_id",
            name="ck_plugin_conflict_canonical_pair",
        ),
        sa.ForeignKeyConstraint(
            ["plugin_a_id"],
            ["market_plugins.id"],
            name=op.f("fk_plugin_conflict_rules_plugin_a_id_market_plugins"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plugin_b_id"],
            ["market_plugins.id"],
            name=op.f("fk_plugin_conflict_rules_plugin_b_id_market_plugins"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plugin_conflict_rules")),
        sa.UniqueConstraint("plugin_a_id", "plugin_b_id", name="uq_plugin_conflict_pair"),
    )
    op.create_index(
        op.f("ix_plugin_conflict_rules_plugin_a_id"),
        "plugin_conflict_rules",
        ["plugin_a_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_plugin_conflict_rules_plugin_b_id"),
        "plugin_conflict_rules",
        ["plugin_b_id"],
        unique=False,
    )
    op.create_table(
        "servers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("ssh_port", sa.Integer(), nullable=False),
        sa.Column("ssh_user", sa.String(length=100), nullable=False),
        sa.Column(
            "auth_type",
            sa.Enum(
                "PASSWORD", "KEY_FILE", name="auth_type", native_enum=False, create_constraint=False
            ),
            nullable=False,
        ),
        sa.Column("ssh_password", sa.String(length=255), nullable=True),
        sa.Column("ssh_key_path", sa.String(length=500), nullable=True),
        sa.Column("sudo_password", sa.String(length=255), nullable=True),
        sa.Column("game_port", sa.Integer(), nullable=False),
        sa.Column("game_directory", sa.String(length=500), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "DEPLOYING",
                "RUNNING",
                "STOPPED",
                "ERROR",
                "UNKNOWN",
                name="server_status",
                native_enum=False,
                create_constraint=False,
            ),
            nullable=True,
        ),
        sa.Column("server_name", sa.String(length=255), nullable=False),
        sa.Column("server_password", sa.String(length=255), nullable=True),
        sa.Column("rcon_password", sa.String(length=255), nullable=True),
        sa.Column("steam_account_token", sa.String(length=255), nullable=True),
        sa.Column("default_map", sa.String(length=100), nullable=False),
        sa.Column("max_players", sa.Integer(), nullable=False),
        sa.Column("game_mode", sa.String(length=50), nullable=False),
        sa.Column("game_type", sa.String(length=50), nullable=False),
        sa.Column("additional_parameters", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=100), nullable=True),
        sa.Column("client_port", sa.Integer(), nullable=True),
        sa.Column("tv_port", sa.Integer(), nullable=True),
        sa.Column("tv_enable", sa.Boolean(), nullable=False),
        sa.Column("api_key", sa.String(length=64), nullable=True),
        sa.Column("backend_url", sa.String(length=500), nullable=True),
        sa.Column("auto_clear_crash_hours", sa.Integer(), nullable=True),
        sa.Column("last_status_check", sa.DateTime(), nullable=True),
        sa.Column("enable_panel_monitoring", sa.Boolean(), nullable=False),
        sa.Column("monitor_interval_seconds", sa.Integer(), nullable=False),
        sa.Column("auto_restart_on_crash", sa.Boolean(), nullable=False),
        sa.Column("manual_stop_requested", sa.Boolean(), nullable=False),
        sa.Column("a2s_query_host", sa.String(length=255), nullable=True),
        sa.Column("a2s_query_port", sa.Integer(), nullable=True),
        sa.Column("enable_a2s_monitoring", sa.Boolean(), nullable=False),
        sa.Column("a2s_failure_threshold", sa.Integer(), nullable=False),
        sa.Column("a2s_check_interval_seconds", sa.Integer(), nullable=False),
        sa.Column("current_game_version", sa.String(length=50), nullable=True),
        sa.Column("enable_auto_update", sa.Boolean(), nullable=False),
        sa.Column("update_check_interval_hours", sa.Float(), nullable=False),
        sa.Column("last_update_check", sa.DateTime(), nullable=True),
        sa.Column("last_update_time", sa.DateTime(), nullable=True),
        sa.Column("enable_plugin_auto_update", sa.Boolean(), nullable=False),
        sa.Column("plugin_update_check_interval_hours", sa.Float(), nullable=False),
        sa.Column("last_plugin_update_check", sa.DateTime(), nullable=True),
        sa.Column("enable_plugin_post_update_commands", sa.Boolean(), nullable=False),
        sa.Column(
            "plugin_post_update_command_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("map_pool_sync_url", sa.String(length=4096), nullable=True),
        sa.Column("cpu_affinity", sa.String(length=500), nullable=True),
        sa.Column("session_manager", sa.String(length=16), nullable=False),
        sa.Column("github_proxy", sa.String(length=500), nullable=True),
        sa.Column("use_panel_proxy", sa.Boolean(), nullable=False),
        sa.Column("discord_notifications_enabled", sa.Boolean(), nullable=False),
        sa.Column("discord_webhook_url", sa.String(length=1000), nullable=True),
        sa.Column("discord_channel_name", sa.String(length=255), nullable=True),
        sa.Column("discord_notify_auto_updates", sa.Boolean(), nullable=False),
        sa.Column("discord_notify_manual_updates", sa.Boolean(), nullable=False),
        sa.Column("discord_notify_plugin_updates", sa.Boolean(), nullable=False),
        sa.Column("discord_notify_s3_backups", sa.Boolean(), nullable=False),
        sa.Column("discord_notify_crash_restarts", sa.Boolean(), nullable=False),
        sa.Column("discord_crash_restart_min_interval_minutes", sa.Integer(), nullable=False),
        sa.Column("last_ssh_success", sa.DateTime(), nullable=True),
        sa.Column("last_ssh_failure", sa.DateTime(), nullable=True),
        sa.Column("consecutive_ssh_failures", sa.Integer(), nullable=False),
        sa.Column("is_ssh_down", sa.Boolean(), nullable=False),
        sa.Column("enable_ssh_health_monitoring", sa.Boolean(), nullable=False),
        sa.Column("ssh_health_check_interval_hours", sa.Integer(), nullable=False),
        sa.Column("ssh_health_failure_threshold", sa.Integer(), nullable=False),
        sa.Column("last_ssh_health_check", sa.DateTime(), nullable=True),
        sa.Column("ssh_health_status", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("last_deployed", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.CheckConstraint(
            "auth_type IN ('PASSWORD', 'KEY_FILE')",
            name="ck_servers_auth_type",
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'DEPLOYING', 'RUNNING', 'STOPPED', 'ERROR', 'UNKNOWN')",
            name="ck_servers_server_status",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_servers_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_servers")),
    )
    op.create_index(op.f("ix_servers_api_key"), "servers", ["api_key"], unique=True)
    op.create_index(op.f("ix_servers_name"), "servers", ["name"], unique=False)
    op.create_index(op.f("ix_servers_user_id"), "servers", ["user_id"], unique=False)
    op.create_table(
        "ssh_servers_sudo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("ssh_port", sa.Integer(), nullable=False),
        sa.Column("sudo_user", sa.String(length=100), nullable=False),
        sa.Column("sudo_password", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_ssh_servers_sudo_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ssh_servers_sudo")),
    )
    op.create_index(
        op.f("ix_ssh_servers_sudo_user_id"), "ssh_servers_sudo", ["user_id"], unique=False
    )
    op.create_table(
        "user_ai_settings",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=True),
        sa.Column("model", sa.String(length=255), nullable=True),
        sa.Column("api_key_encrypted", sa.Text(), nullable=True),
        sa.Column("reasoning_effort", sa.String(length=16), nullable=True),
        sa.Column("temperature", sa.Float(), nullable=True),
        sa.Column("top_p", sa.Float(), nullable=True),
        sa.Column("max_completion_tokens", sa.Integer(), nullable=False),
        sa.Column("token_limit_parameter", sa.String(length=32), nullable=False),
        sa.Column("frequency_penalty", sa.Float(), nullable=True),
        sa.Column("presence_penalty", sa.Float(), nullable=True),
        sa.Column("verbosity", sa.String(length=16), nullable=True),
        sa.Column("parallel_tool_calls", sa.Boolean(), nullable=True),
        sa.Column("provider_tested", sa.Boolean(), nullable=False),
        sa.Column("tool_calling_tested", sa.Boolean(), nullable=False),
        sa.Column("streaming_tested", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_ai_settings_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_ai_settings")),
    )
    op.create_table(
        "ai_conversations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["servers.id"],
            name=op.f("fk_ai_conversations_server_id_servers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_ai_conversations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_conversations")),
    )
    op.create_index(
        op.f("ix_ai_conversations_server_id"), "ai_conversations", ["server_id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_conversations_user_id"), "ai_conversations", ["user_id"], unique=False
    )
    op.create_index(
        "ix_ai_conversations_user_updated",
        "ai_conversations",
        ["user_id", "updated_at"],
        unique=False,
    )
    op.create_table(
        "custom_commands",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("target", sa.String(length=30), nullable=False),
        sa.Column("commands", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["servers.id"],
            name=op.f("fk_custom_commands_server_id_servers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_custom_commands_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_custom_commands")),
    )
    op.create_index(
        op.f("ix_custom_commands_server_id"), "custom_commands", ["server_id"], unique=False
    )
    op.create_index(
        "ix_custom_commands_server_user_created",
        "custom_commands",
        ["server_id", "user_id", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_commands_user_id"), "custom_commands", ["user_id"], unique=False
    )
    op.create_table(
        "managed_plugins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("source_key", sa.String(length=500), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("repo_url", sa.String(length=500), nullable=True),
        sa.Column("market_plugin_id", sa.Integer(), nullable=True),
        sa.Column("framework_key", sa.String(length=100), nullable=True),
        sa.Column("installed_release_id", sa.String(length=100), nullable=True),
        sa.Column("installed_version", sa.String(length=100), nullable=False),
        sa.Column("latest_version", sa.String(length=100), nullable=True),
        sa.Column("asset_glob", sa.String(length=500), nullable=True),
        sa.Column("custom_install_path", sa.String(length=255), nullable=True),
        sa.Column("install_recipe_id", sa.Integer(), nullable=True),
        sa.Column("installed_asset_name", sa.String(length=500), nullable=True),
        sa.Column("archive_sha256", sa.String(length=64), nullable=True),
        sa.Column("config_policy", sa.String(length=32), nullable=False),
        sa.Column("exclude_dirs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("exclude_files", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("auto_update_enabled", sa.Boolean(), nullable=False),
        sa.Column("backup_before_update", sa.Boolean(), nullable=False),
        sa.Column("restart_after_update", sa.Boolean(), nullable=False),
        sa.Column("last_check_at", sa.DateTime(), nullable=True),
        sa.Column("last_update_at", sa.DateTime(), nullable=True),
        sa.Column("last_status", sa.String(length=30), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["install_recipe_id"],
            ["github_install_recipes.id"],
            name=op.f("fk_managed_plugins_install_recipe_id_github_install_recipes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["market_plugin_id"],
            ["market_plugins.id"],
            name=op.f("fk_managed_plugins_market_plugin_id_market_plugins"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["servers.id"],
            name=op.f("fk_managed_plugins_server_id_servers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_managed_plugins")),
        sa.UniqueConstraint(
            "server_id", "source_type", "source_key", name="uq_managed_plugin_source"
        ),
    )
    op.create_index(
        op.f("ix_managed_plugins_server_id"), "managed_plugins", ["server_id"], unique=False
    )
    op.create_table(
        "plugin_config_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("relative_path", sa.String(length=1000), nullable=False),
        sa.Column("path_hash", sa.String(length=64), nullable=False),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["servers.id"],
            name=op.f("fk_plugin_config_sources_server_id_servers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plugin_config_sources")),
        sa.UniqueConstraint("server_id", "path_hash", name="uq_plugin_config_source_path"),
    )
    op.create_index(
        op.f("ix_plugin_config_sources_server_id"),
        "plugin_config_sources",
        ["server_id"],
        unique=False,
    )
    op.create_table(
        "scheduled_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("schedule_type", sa.String(length=50), nullable=False),
        sa.Column("schedule_value", sa.String(length=255), nullable=False),
        sa.Column("last_run", sa.DateTime(), nullable=True),
        sa.Column("next_run", sa.DateTime(), nullable=True),
        sa.Column("run_count", sa.Integer(), nullable=False),
        sa.Column("last_status", sa.String(length=50), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["servers.id"],
            name=op.f("fk_scheduled_tasks_server_id_servers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scheduled_tasks")),
    )
    op.create_index(
        "ix_scheduled_tasks_due",
        "scheduled_tasks",
        ["next_run"],
        unique=False,
        postgresql_where=sa.text("enabled IS TRUE"),
    )
    op.create_index(
        op.f("ix_scheduled_tasks_server_id"), "scheduled_tasks", ["server_id"], unique=False
    )
    op.create_table(
        "ai_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("tool_calls", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("tool_call_id", sa.String(length=100), nullable=True),
        sa.Column("tool_name", sa.String(length=100), nullable=True),
        sa.Column("visible", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["ai_conversations.id"],
            name=op.f("fk_ai_messages_conversation_id_ai_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_messages")),
    )
    op.create_index(
        op.f("ix_ai_messages_conversation_id"), "ai_messages", ["conversation_id"], unique=False
    )
    op.create_index(
        "ix_ai_messages_conversation_id_id", "ai_messages", ["conversation_id", "id"], unique=False
    )
    op.create_table(
        "ai_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["ai_conversations.id"],
            name=op.f("fk_ai_runs_conversation_id_ai_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["servers.id"],
            name=op.f("fk_ai_runs_server_id_servers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_ai_runs_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_runs")),
    )
    op.create_index(
        op.f("ix_ai_runs_conversation_id"), "ai_runs", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_ai_runs_status"), "ai_runs", ["status"], unique=False)
    op.create_index(op.f("ix_ai_runs_user_id"), "ai_runs", ["user_id"], unique=False)
    op.create_table(
        "managed_plugin_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("managed_plugin_id", sa.Integer(), nullable=False),
        sa.Column("relative_path", sa.String(length=1000), nullable=False),
        sa.Column("path_hash", sa.String(length=64), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("file_role", sa.String(length=32), nullable=False),
        sa.Column("preserved", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["managed_plugin_id"],
            ["managed_plugins.id"],
            name=op.f("fk_managed_plugin_files_managed_plugin_id_managed_plugins"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_managed_plugin_files")),
        sa.UniqueConstraint("managed_plugin_id", "path_hash", name="uq_managed_plugin_file"),
    )
    op.create_index(
        op.f("ix_managed_plugin_files_managed_plugin_id"),
        "managed_plugin_files",
        ["managed_plugin_id"],
        unique=False,
    )
    op.create_table(
        "ai_tool_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("tool_call_id", sa.String(length=100), nullable=False),
        sa.Column("tool_name", sa.String(length=100), nullable=False),
        sa.Column("arguments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("arguments_hash", sa.String(length=64), nullable=False),
        sa.Column("risk", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column("approved_by", sa.Integer(), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("approval_expires_at", sa.DateTime(), nullable=True),
        sa.Column("plan_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("progress_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("progress_updated_at", sa.DateTime(), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
            name=op.f("fk_ai_tool_runs_approved_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ai_runs.id"],
            name=op.f("fk_ai_tool_runs_run_id_ai_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_tool_runs")),
        sa.UniqueConstraint("run_id", "tool_call_id", name="uq_ai_tool_run_call"),
    )
    op.create_index(
        op.f("ix_ai_tool_runs_approval_expires_at"),
        "ai_tool_runs",
        ["approval_expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_ai_tool_runs_run_created", "ai_tool_runs", ["run_id", "created_at", "id"], unique=False
    )
    op.create_index(op.f("ix_ai_tool_runs_run_id"), "ai_tool_runs", ["run_id"], unique=False)
    op.create_table(
        "plugin_diagnostic_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("requested_by", sa.Integer(), nullable=False),
        sa.Column("server_owner_id", sa.Integer(), nullable=False),
        sa.Column("ai_run_id", sa.String(length=36), nullable=True),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("plan_hash", sa.String(length=64), nullable=False),
        sa.Column("candidate_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("original_server_running", sa.Boolean(), nullable=False),
        sa.Column("health_policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("culprit_keys", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("start_attempts", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ai_run_id"],
            ["ai_runs.id"],
            name=op.f("fk_plugin_diagnostic_runs_ai_run_id_ai_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
            name=op.f("fk_plugin_diagnostic_runs_requested_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["servers.id"],
            name=op.f("fk_plugin_diagnostic_runs_server_id_servers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plugin_diagnostic_runs")),
    )
    op.create_index(
        op.f("ix_plugin_diagnostic_runs_server_id"),
        "plugin_diagnostic_runs",
        ["server_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_plugin_diagnostic_runs_status"), "plugin_diagnostic_runs", ["status"], unique=False
    )
    op.create_table(
        "plugin_diagnostic_steps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("diagnostic_run_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("phase", sa.String(length=64), nullable=False),
        sa.Column("candidate_keys", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("healthy", sa.Boolean(), nullable=True),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["diagnostic_run_id"],
            ["plugin_diagnostic_runs.id"],
            name=op.f("fk_plugin_diagnostic_steps_diagnostic_run_id_plugin_diagnostic_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plugin_diagnostic_steps")),
        sa.UniqueConstraint("diagnostic_run_id", "sequence", name="uq_diagnostic_step_sequence"),
    )
    op.create_index(
        op.f("ix_plugin_diagnostic_steps_diagnostic_run_id"),
        "plugin_diagnostic_steps",
        ["diagnostic_run_id"],
        unique=False,
    )
    op.create_table(
        "plugin_quarantine_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("diagnostic_run_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_key", sa.String(length=500), nullable=False),
        sa.Column("source_relative_path", sa.String(length=1000), nullable=False),
        sa.Column("quarantine_relative_path", sa.String(length=1000), nullable=False),
        sa.Column("source_revision", sa.String(length=128), nullable=False),
        sa.Column("is_quarantined", sa.Boolean(), nullable=False),
        sa.Column("is_culprit", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.Column("restored_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["diagnostic_run_id"],
            ["plugin_diagnostic_runs.id"],
            name=op.f("fk_plugin_quarantine_entries_diagnostic_run_id_plugin_diagnostic_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plugin_quarantine_entries")),
        sa.UniqueConstraint("diagnostic_run_id", "candidate_key", name="uq_quarantine_candidate"),
    )
    op.create_index(
        op.f("ix_plugin_quarantine_entries_diagnostic_run_id"),
        "plugin_quarantine_entries",
        ["diagnostic_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_plugin_quarantine_entries_is_quarantined"),
        "plugin_quarantine_entries",
        ["is_quarantined"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_plugin_quarantine_entries_is_quarantined"), table_name="plugin_quarantine_entries"
    )
    op.drop_index(
        op.f("ix_plugin_quarantine_entries_diagnostic_run_id"),
        table_name="plugin_quarantine_entries",
    )
    op.drop_table("plugin_quarantine_entries")
    op.drop_index(
        op.f("ix_plugin_diagnostic_steps_diagnostic_run_id"), table_name="plugin_diagnostic_steps"
    )
    op.drop_table("plugin_diagnostic_steps")
    op.drop_index(op.f("ix_plugin_diagnostic_runs_status"), table_name="plugin_diagnostic_runs")
    op.drop_index(op.f("ix_plugin_diagnostic_runs_server_id"), table_name="plugin_diagnostic_runs")
    op.drop_table("plugin_diagnostic_runs")
    op.drop_index(op.f("ix_ai_tool_runs_run_id"), table_name="ai_tool_runs")
    op.drop_index("ix_ai_tool_runs_run_created", table_name="ai_tool_runs")
    op.drop_index(op.f("ix_ai_tool_runs_approval_expires_at"), table_name="ai_tool_runs")
    op.drop_table("ai_tool_runs")
    op.drop_index(
        op.f("ix_managed_plugin_files_managed_plugin_id"), table_name="managed_plugin_files"
    )
    op.drop_table("managed_plugin_files")
    op.drop_index(op.f("ix_ai_runs_user_id"), table_name="ai_runs")
    op.drop_index(op.f("ix_ai_runs_status"), table_name="ai_runs")
    op.drop_index(op.f("ix_ai_runs_conversation_id"), table_name="ai_runs")
    op.drop_table("ai_runs")
    op.drop_index("ix_ai_messages_conversation_id_id", table_name="ai_messages")
    op.drop_index(op.f("ix_ai_messages_conversation_id"), table_name="ai_messages")
    op.drop_table("ai_messages")
    op.drop_index(op.f("ix_scheduled_tasks_server_id"), table_name="scheduled_tasks")
    op.drop_index(
        "ix_scheduled_tasks_due",
        table_name="scheduled_tasks",
        postgresql_where=sa.text("enabled IS TRUE"),
    )
    op.drop_table("scheduled_tasks")
    op.drop_index(op.f("ix_plugin_config_sources_server_id"), table_name="plugin_config_sources")
    op.drop_table("plugin_config_sources")
    op.drop_index(op.f("ix_managed_plugins_server_id"), table_name="managed_plugins")
    op.drop_table("managed_plugins")
    op.drop_index(op.f("ix_custom_commands_user_id"), table_name="custom_commands")
    op.drop_index("ix_custom_commands_server_user_created", table_name="custom_commands")
    op.drop_index(op.f("ix_custom_commands_server_id"), table_name="custom_commands")
    op.drop_table("custom_commands")
    op.drop_index("ix_ai_conversations_user_updated", table_name="ai_conversations")
    op.drop_index(op.f("ix_ai_conversations_user_id"), table_name="ai_conversations")
    op.drop_index(op.f("ix_ai_conversations_server_id"), table_name="ai_conversations")
    op.drop_table("ai_conversations")
    op.drop_table("user_ai_settings")
    op.drop_index(op.f("ix_ssh_servers_sudo_user_id"), table_name="ssh_servers_sudo")
    op.drop_table("ssh_servers_sudo")
    op.drop_index(op.f("ix_servers_user_id"), table_name="servers")
    op.drop_index(op.f("ix_servers_name"), table_name="servers")
    op.drop_index(op.f("ix_servers_api_key"), table_name="servers")
    op.drop_table("servers")
    op.drop_index(op.f("ix_plugin_conflict_rules_plugin_b_id"), table_name="plugin_conflict_rules")
    op.drop_index(op.f("ix_plugin_conflict_rules_plugin_a_id"), table_name="plugin_conflict_rules")
    op.drop_table("plugin_conflict_rules")
    op.drop_index(op.f("ix_password_reset_tokens_user_id"), table_name="password_reset_tokens")
    op.drop_index(op.f("ix_password_reset_tokens_token"), table_name="password_reset_tokens")
    op.drop_table("password_reset_tokens")
    op.drop_index(op.f("ix_initialized_servers_user_id"), table_name="initialized_servers")
    op.drop_index("ix_initialized_servers_user_created", table_name="initialized_servers")
    op.drop_table("initialized_servers")
    op.drop_index(op.f("ix_github_install_recipes_repo_url"), table_name="github_install_recipes")
    op.drop_table("github_install_recipes")
    op.drop_index("uq_users_username_ci", table_name="users")
    op.drop_index("uq_users_email_ci", table_name="users")
    op.drop_index(op.f("ix_users_google_id"), table_name="users")
    op.drop_index(op.f("ix_users_api_key"), table_name="users")
    op.drop_table("users")
    op.drop_table("system_settings")
    op.drop_index(op.f("ix_monitoring_logs_server_id"), table_name="monitoring_logs")
    op.drop_index(op.f("ix_monitoring_logs_created_at"), table_name="monitoring_logs")
    op.drop_table("monitoring_logs")
    op.drop_index(op.f("ix_market_plugins_title"), table_name="market_plugins")
    op.drop_index(op.f("ix_market_plugins_github_url"), table_name="market_plugins")
    op.drop_table("market_plugins")
    op.drop_index(op.f("ix_deployment_logs_server_id"), table_name="deployment_logs")
    op.drop_index("ix_deployment_logs_server_created", table_name="deployment_logs")
    op.drop_table("deployment_logs")
    op.drop_table("ai_system_settings")
    # ### end Alembic commands ###
