"""Typed, permission-checked tools exposed to the AI model."""

from __future__ import annotations

from modules.models import (
    CustomCommand,
    ManagedPlugin,
    MarketPlugin,
    PluginCategory,
    Server,
    ServerStatus,
    User,
)
from modules.utils import get_current_time
from services.ai.tools.approvals import build_approval_summary
from services.ai.tools.context import (
    CapabilityResolver,
    EventEmitter,
    ToolContext,
    ToolHandler,
    ToolSpec,
    _connect,
    _require_active_user,
    _require_current_server,
    _safe_relative_path,
    _saved_command_hash,
    canonical_arguments,
)
from services.ai.tools.files import (
    _css_log_root,
    _safe_css_log_name,
    list_css_error_logs,
    patch_server_text_file,
    read_css_error_log,
    read_game_console,
    read_server_text_file,
    search_server_files,
    tail_server_log,
)
from services.ai.tools.github import (
    _optional_linux_runtime_profile,
    apply_github_plugin_install,
    inspect_github_plugin,
    plan_github_plugin_install,
    search_github_cs2_plugins,
)
from services.ai.tools.plugins import (
    _market_release_selection_preview,
    apply_managed_plugin_upgrade,
    apply_plugin_plan,
    execute_plugin_crash_isolation,
    get_plugin_crash_isolation,
    list_installed_plugins,
    lookup_cs2_knowledge,
    plan_managed_plugin_upgrade,
    plan_plugin_crash_isolation,
    plan_plugin_install,
    restore_plugin_quarantine,
    search_plugin_market,
)
from services.ai.tools.registry import (
    TOOL_SPECS,
    TOOLS_BY_NAME,
    _control_capabilities,
    _server_operation_capabilities,
    execute_tool,
    tool_definitions,
)
from services.ai.tools.schemas import (
    ApplyManagedPluginUpgradeInput,
    ApplyPluginPlanInput,
    ApplyServerStartupPlanInput,
    ApplyWorkshopPlanInput,
    ChangeCurrentMapInput,
    CSSLogListInput,
    CSSLogReadInput,
    DiagnosticExecuteInput,
    DiagnosticPlanInput,
    DiagnosticRunInput,
    EmptyInput,
    FilePatchInput,
    FileReadInput,
    FileSearchInput,
    GameConsoleCommandInput,
    GameConsoleReadInput,
    GitHubApplyInput,
    GitHubInspectInput,
    GitHubPlanInput,
    GitHubSearchInput,
    KnowledgeInput,
    ManagedPluginUpgradeInput,
    MapPoolSearchInput,
    PluginPlanInput,
    PluginSearchInput,
    SavedHostCommandInput,
    ServerControlInput,
    ServerOperationInput,
    ServerStartupPlanInput,
    TailLogInput,
    ToolInput,
    WorkshopPlanInput,
)
from services.ai.tools.server import (
    apply_server_startup_update,
    change_current_map,
    control_server,
    execute_saved_host_command,
    inspect_server,
    list_saved_host_commands,
    list_servers,
    plan_server_startup_update,
    run_server_operation,
    search_map_pool,
    send_game_console_command,
)
from services.ai.tools.workshop import apply_workshop_map, plan_workshop_map
from services.ai_access import authorized_server, enforce_agent_rate_limit
from services.ai_knowledge import KNOWLEDGE_TOPICS, lookup_knowledge
from services.ai_security import redact_sensitive_text, sanitize_tool_result
from services.maintenance_lock import maintenance_lock_service
from services.plugin_inventory_service import (
    PluginInventoryError,
    inspect_remote_plugin_inventory,
    installation_evidence,
)
from services.server_lifecycle_policy import apply_user_lifecycle_intent
from services.ssh_manager import SSHManager

__all__ = [
    "ApplyManagedPluginUpgradeInput",
    "ApplyPluginPlanInput",
    "ApplyServerStartupPlanInput",
    "ApplyWorkshopPlanInput",
    "CSSLogListInput",
    "CSSLogReadInput",
    "CapabilityResolver",
    "ChangeCurrentMapInput",
    "CustomCommand",
    "DiagnosticExecuteInput",
    "DiagnosticPlanInput",
    "DiagnosticRunInput",
    "EmptyInput",
    "EventEmitter",
    "FilePatchInput",
    "FileReadInput",
    "FileSearchInput",
    "GameConsoleCommandInput",
    "GameConsoleReadInput",
    "GitHubApplyInput",
    "GitHubInspectInput",
    "GitHubPlanInput",
    "GitHubSearchInput",
    "KNOWLEDGE_TOPICS",
    "KnowledgeInput",
    "ManagedPlugin",
    "ManagedPluginUpgradeInput",
    "MapPoolSearchInput",
    "MarketPlugin",
    "PluginCategory",
    "PluginPlanInput",
    "PluginInventoryError",
    "PluginSearchInput",
    "SSHManager",
    "SavedHostCommandInput",
    "Server",
    "ServerControlInput",
    "ServerOperationInput",
    "ServerStartupPlanInput",
    "ServerStatus",
    "TOOL_SPECS",
    "TOOLS_BY_NAME",
    "TailLogInput",
    "ToolContext",
    "ToolHandler",
    "ToolInput",
    "ToolSpec",
    "User",
    "WorkshopPlanInput",
    "_connect",
    "_control_capabilities",
    "_css_log_root",
    "_market_release_selection_preview",
    "_optional_linux_runtime_profile",
    "_require_active_user",
    "_require_current_server",
    "_safe_css_log_name",
    "_safe_relative_path",
    "_saved_command_hash",
    "_server_operation_capabilities",
    "apply_github_plugin_install",
    "apply_managed_plugin_upgrade",
    "apply_plugin_plan",
    "apply_server_startup_update",
    "apply_user_lifecycle_intent",
    "apply_workshop_map",
    "authorized_server",
    "build_approval_summary",
    "canonical_arguments",
    "change_current_map",
    "control_server",
    "enforce_agent_rate_limit",
    "execute_plugin_crash_isolation",
    "execute_saved_host_command",
    "execute_tool",
    "get_current_time",
    "get_plugin_crash_isolation",
    "inspect_github_plugin",
    "inspect_server",
    "inspect_remote_plugin_inventory",
    "installation_evidence",
    "list_css_error_logs",
    "list_installed_plugins",
    "list_saved_host_commands",
    "list_servers",
    "lookup_cs2_knowledge",
    "lookup_knowledge",
    "maintenance_lock_service",
    "patch_server_text_file",
    "plan_github_plugin_install",
    "plan_managed_plugin_upgrade",
    "plan_plugin_crash_isolation",
    "plan_plugin_install",
    "plan_server_startup_update",
    "plan_workshop_map",
    "read_css_error_log",
    "read_game_console",
    "read_server_text_file",
    "redact_sensitive_text",
    "restore_plugin_quarantine",
    "run_server_operation",
    "sanitize_tool_result",
    "search_github_cs2_plugins",
    "search_map_pool",
    "search_plugin_market",
    "search_server_files",
    "send_game_console_command",
    "tail_server_log",
    "tool_definitions",
]
