#!/usr/bin/env python3
"""Export hash-pinned dependencies with pip-compatible minor-version markers."""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
MINOR_BOUNDARY = re.compile(r"\bpython_full_version\s+(>=|<)\s+(['\"])(\d+\.\d+)\2")
HEADER = (
    "# This file was autogenerated by scripts/export_requirements.py from uv.lock.\n"
    "# Regenerate with: uv run python scripts/export_requirements.py\n"
)


def preserve_minor_version_markers(content: str) -> str:
    """Keep uv's release-only boundaries valid for Python release candidates.

    uv strips prerelease suffixes when evaluating Python version markers. pip
    evaluates the full PEP 440 version instead, leaving rc3 outside both <3.15
    and >=3.15. Minor-version comparisons agree on both stable and RC builds.
    Patch-level comparisons, package versions, platforms and hashes stay intact.
    """
    return MINOR_BOUNDARY.sub(r"python_version \1 \2\3\2", content)


def main() -> None:
    result = subprocess.run(
        [
            "uv",
            "export",
            "--locked",
            "--no-dev",
            "--no-emit-project",
            "--no-header",
            "--format",
            "requirements-txt",
        ],
        cwd=PROJECT_ROOT,
        capture_output=True,
        encoding="utf-8",
        check=True,
    )
    (PROJECT_ROOT / "requirements.txt").write_text(
        HEADER + preserve_minor_version_markers(result.stdout), encoding="utf-8"
    )


if __name__ == "__main__":
    main()
