#!/usr/bin/env python3
"""Export hash-pinned dependencies with pip-compatible minor-version markers."""

from __future__ import annotations

import re
import subprocess
from argparse import ArgumentParser
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
MINOR_BOUNDARY = re.compile(r"\bpython_full_version\s+(>=|<)\s+(['\"])(\d+\.\d+)\2")
HEADER = (
    "# This file was autogenerated by scripts/export_requirements.py from uv.lock.\n"
    "# Regenerate with: uv run python scripts/export_requirements.py\n"
)


def preserve_minor_version_markers(content: str) -> str:
    """Keep uv's release-only boundaries valid for Python release candidates.

    uv strips prerelease suffixes when evaluating Python version markers. pip
    evaluates the full PEP 440 version instead, leaving rc3 outside both <3.15
    and >=3.15. Minor-version comparisons agree on both stable and RC builds.
    Patch-level comparisons, package versions, platforms and hashes stay intact.
    """
    return MINOR_BOUNDARY.sub(r"python_version \1 \2\3\2", content)


def export_requirements() -> str:
    result = subprocess.run(
        [
            "uv",
            "export",
            "--locked",
            "--no-dev",
            "--no-emit-project",
            "--no-header",
            "--format",
            "requirements-txt",
        ],
        cwd=PROJECT_ROOT,
        capture_output=True,
        encoding="utf-8",
        check=True,
    )
    return HEADER + preserve_minor_version_markers(result.stdout)


def main(argv: list[str] | None = None) -> int:
    parser = ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check the export without writing it")
    options = parser.parse_args(argv)
    content = export_requirements()
    destination = PROJECT_ROOT / "requirements.txt"
    if options.check:
        if not destination.is_file() or destination.read_text(encoding="utf-8") != content:
            print("requirements.txt does not match the hash-pinned export of uv.lock.")
            print("Regenerate with: uv run python scripts/export_requirements.py")
            return 1
        print("Hash-pinned dependency export matches uv.lock.")
        return 0
    destination.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
